import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<footer>
				Authored by
				<a target="_blank" rel="noopener noreferrer">
					Aaryan
				</a>
				<a target="_blank" rel="noopener noreferer">Edwin</a>
								<a target="_blank" rel="noopener noreferer">Jubril</a>

			</footer>
		</div>
	)
}

export default Home
