import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<footer className={styles.footer}>
				Authored by
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Aaryan
				</a>
				<a>Edwin</a>
				<a>Jubril</a>
			</footer>
		</div>
	)
}

export default Home
